# config/secrets.yml

development:
  secret_key_base: long_generated_key
  stripe_publishable_key: pk_test_51LupHoBDqdN1B7igUaX9wzOrXnyMeU4u0xjLA45opuv6vnBbhMtROli3ga5DJl6D9GCAQVB4NeM0oiALaKqIW83a006DTyJY9p
  stripe_secret_key: sk_test_51LupHoBDqdN1B7igFyWQNt5Nl5VLza5WOLhWHJtXvroqBHTebRxgXha5ewxwiV3T3VnpkcvEVx2qGQtQWJgdo1Wn00x9DribNO
